
appName: iot-stream-producer
container_name: iot-stream-producer-container
port: 9009

service:
  port: 8010
  type: ClusterIP

namespace: dev

deployment:
  replicas: 3
  
configmap:
  name: iot-stream-producer-configmap
  data:
    CUSTOM_HEADER: 'This app was deployed with helm!'

image:
  name: e4espootin/iot-stream-producer
  tag: latest

# secret:
#   Apikey: KEY
#   secret_config_name: apikey-openweathermap